### ISSUE TITLE
approve_after_days  option is not available on approval_rule 

### ISSUE THREAD

**Issue by surendarkaniops** [cloudposse/terraform-aws-ssm-patch-manager#8]
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[![Slack Community](https://slack.cloudposse.com/badge.svg)](https://slack.cloudposse.com)

## Describe the Feature
approve_after_days  - The cutoff date for auto approval of released patches. Any patches released on or before this date are installed automatically. Date is formatted as YYYY-MM-DD

approve_after_days   option is missing in creating patch base line rule
## Use Case
approve_after_days  - can help us to approve the update within the timeline. so that we can test patches in development and we can approve to production 
Is your feature request related to a problem/challenge you are trying to solve? Please provide some additional context of why this feature or capability will be valuable.

## Describe Ideal Solution

A clear and concise description of what you want to happen. If you don't know, that's okay.

## Alternatives Considered

Explain what alternative solutions or features you've considered.

**Comment by jamengual** [comment]
PRs are welcome, if you think you need this feature, please feel free to create a PR and we will review it.

**Comment by surendarkaniops** [comment]
> PRs are welcome, if you think you need this feature, please feel free to create a PR and we will review it.

Raised the PR but it got failed with some naming . so can you please help 
https://github.com/cloudposse/terraform-aws-ssm-patch-manager/pull/9#event-5546856081

![image](https://user-images.githubusercontent.com/34432247/139630034-266ce34f-29fa-4e43-aa91-7ce2a03668d1.png)
